<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Admin',
                'emp_id' => 'ECS-admin',
                'email' => 'admin@ecscloudinfotech.com',
                'join_date' => '02/01/2020',
                'password' => Hash::make('admin@1234'), 
                'role' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manoj Prabhakar R',
                'emp_id' => 'ECS-27052201',
                'email' => 'manoj@ecscloudinfotech.com',
                'join_date' => '02/01/2020',
                'password' => Hash::make('Manoj@2201'), // Use Hash for secure passwords
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vishnu Priya S',
                'emp_id' => 'ECS-27052202',
                'email' => 'priya@ecscloudinfotech.com',
                'join_date' => '07/12/2020',
                'password' => Hash::make('Vishnu@2202'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kavitha M',
                'emp_id' => 'ECS-27052203',
                'email' => 'kavitha@ecscloudinfotech.com',
                'join_date' => '28/03/2022',
                'password' => Hash::make('Kavitha@2203'),
                'role' => '2' ,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yalini S A',
                'emp_id' => 'ECS-27052204',
                'email' => 'yalini@ecscloudinfotech.com',
                'join_date' => '11/04/2022',
                'password' => Hash::make('Yalini@2204'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leela Prasanna D',
                'emp_id' => 'ECS-27052205',
                'email' => 'leela@ecscloudinfotech.com',
                'join_date' => '01/07/2023',
                'password' => Hash::make('Leela@2205'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chandru R',
                'emp_id' => 'ECS-27052206',
                'email' => 'chandru@ecscloudinfotech.com',
                'join_date' => '01/07/2023',
                'password' => Hash::make('Chandru@2206'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suriya G',
                'emp_id' => 'ECS-27052207',
                'email' => 'surya@ecscloudinfotech.com',
                'join_date' => '01/07/2023',
                'password' => Hash::make('Suriya@2207'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gayathri M',
                'emp_id' => 'ECS-27052208',
                'email' => 'gayathri@ecscloudinfotech.com',
                'join_date' => '14/07/2023',
                'password' => Hash::make('Gayathri@2208'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Poongodi K',
                'emp_id' => 'ECS-27052209',
                'email' => 'poongodi@ecscloudinfotech.com',
                'join_date' => '14/07/2023',
                'password' => Hash::make('Poongodi@2209'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Saravanan M',
                'emp_id' => 'ECS-27052210',
                'email' => 'saravana@ecscloudinfotech.com',
                'join_date' => '14/07/2023',
                'password' => Hash::make('Saravanan@2210'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vignesh D',
                'emp_id' => 'ECS-27052211',
                'email' => 'vignesh@ecscloudinfotech.com',
                'join_date' => '01/08/2023',
                'password' => Hash::make('Vignesh@2211'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ragul Dravid I',
                'emp_id' => 'ECS-27052212',
                'email' => 'ragul@ecscloudinfotech.com',
                'join_date' => '17/01/2024',
                'password' => Hash::make('Ragul@2212'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Antony Karan Raj M',
                'emp_id' => 'ECS-27052213',
                'email' => 'antony@ecscloudinfotech.com',
                'join_date' => '17/01/2024',
                'password' => Hash::make('Antony@2213'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Keerthick Vasan S',
                'emp_id' => 'ECS-27052214',
                'email' => 'keerthick@ecscloudinfotech.com',
                'join_date' => '01/03/2024',
                'password' => Hash::make('Keerthick@2214'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sakthivel J',
                'emp_id' => 'ECS-27052215',
                'email' => 'sakthivel@ecscloudinfotech.com',
                'join_date' => '01/03/2024',
                'password' => Hash::make('Sakthivel@2215'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Harishragavendhar B',
                'emp_id' => 'ECS-27052216',
                'email' => 'harish@ecscloudinfotech.com',
                'join_date' => '01/03/2024',
                'password' => Hash::make('Harishragavendhar@2216'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Prem Kumar V',
                'emp_id' => 'ECS-27052217',
                'email' => 'prem@ecscloudinfotech.com',
                'join_date' => '01/03/2024',
                'password' => Hash::make('Prem@2217'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manikandan S',
                'emp_id' => 'ECS-27052218',
                'email' => 'smani@ecscloudinfotech.com',
                'join_date' => '01/06/2024',
                'password' => Hash::make('Manikandan@2218'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Siva Rama Krishnan',
                'emp_id' => 'ECS-27052219',
                'email' => 'siva@ecscloudinfotech.com',
                'join_date' => '01/06/2024',
                'password' => Hash::make('Siva@2219'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kishore Kumar R',
                'emp_id' => 'ECS-27052220',
                'email' => 'kishorekumar.ravi04@gmail.com',
                'join_date' => '01/07/2024',
                'password' => Hash::make('Kishore@2220'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marimuthu R',
                'emp_id' => 'ECS-27052221',
                'email' => 'sctmari21@gmail.com',
                'join_date' => '01/07/2024',
                'password' => Hash::make('Marimuthu@2221'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sangeetha A',
                'emp_id' => 'ECS-27052222',
                'email' => 'sangeethaecs2000@gmail.com',
                'join_date' => '01/07/2024',
                'password' => Hash::make('Sangeetha@2222'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rohini Devi D',
                'emp_id' => 'ECS-27052223',
                'email' => 'rohinidevi.cloudecs@gmail.com',
                'join_date' => '01/07/2024',
                'password' => Hash::make('Rohini@2223'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sridaran',
                'emp_id' => 'ECS-27052224',
                'email' => 'sridarancloudecs@gmail.com',
                'join_date' => '01/07/2024',
                'password' => Hash::make('Sridaran@2224'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sumaiya',
                'emp_id' => 'ECS-27052225',
                'email' => 'sumaiyaecs211@gmail.com',
                'join_date' => '01/07/2024',
                'password' => Hash::make('Sumaiya@2225'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thulasinathan',
                'emp_id' => 'ECS-27052226',
                'email' => 'thulasinathanecs@gmail.com',
                'join_date' => '01/07/2024',
                'password' => Hash::make('Thulasinathan@2226'),
                'role' => '2' ,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mohit Sudhan S',
                'emp_id' => 'ECS-27052227',
                'email' => 'mohit@ecscloudinfotech.com',
                'join_date' => '01/08/2024',
                'password' => Hash::make('Mohit@2227'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dilip K',
                'emp_id' => 'ECS-27052228',
                'email' => 'dilip@ecscloudinfotech.com',
                'join_date' => '12/08/24',
                'password' => Hash::make('Dilip@2228'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Utkarsh Baghel',
                'emp_id' => 'ECS-27052229',
                'email' => 'utkarshbaghel2@gmail.com',
                'join_date' => '21/08/2024',
                'password' => Hash::make('Utkarsh@2229'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manoj AM',
                'emp_id' => 'ECS-27052230',
                'email' => 'creativeman21276@gmail.com',
                'join_date' => '25/09/2024',
                'password' => Hash::make('Manoj@2230'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nikhil S',
                'emp_id' => 'ECS-27052231',
                'email' => 'nikhilnkm23@gmail.com',
                'join_date' => '01/10/2024',
                'password' => Hash::make('Nikhil@2231'), 
                'role' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ]

        ]);
    }
}
